name: Verify

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PROTEGEPROJECT_BOT_APP_ID }}
          private-key: ${{ secrets.PROTEGEPROJECT_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          gpg-private-key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Build with Maven
        run: mvn --batch-mode verify -Prelease
